baseurl = "https://farrmt.github.io/Projects/"
publishDir = "docs"
title = "Matthew Farr Projects"
author = "farrmt"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Matthew Farr Projects"

[[menu.main]]
    name = "Home"
    url = "https://farrmt.github.io/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/farrmt"
    weight = 2