---
title: "Farr, M.T, Green, D.S., Holekamp, K.E., Roloff, G.J., and Zipkin, E.F. (In Review after Revision) Multi-species hierarchical modeling reveals variable responses of African carnivores to management alternatives. Ecological Applications."
date: "March 21, 2018"
draft: false
output:
  blogdown::html_page
---

I am working with [David Green](http://inr.oregonstate.edu/people/david-green) and the [Holekamp lab](http://www.holekamplab.org/) to quantify the impact of anthropogenic disturbance and management alternatives on the carnivore community within the Masai Mara National Reserve (MMNR), Kenya. Carnivore communities in the Serengeti-Mara ecosystem, including the MMNR, are among the most diverse in the world, but human-wildlife conflict threatens the continuation of this community. To understand the impact of anthropogenic disturbance on the carnivore community, we compare two disparate management regions within the MMNR that are managed by separate entities. The Mara Triangle experiences minimal disturbance while the Talek region contains high frequency of human-wildlife conflict. Using a hierarchical multi-species distance sampling model we estimate the community wide and species-specific effects of the Talek region on carnivore abundance and compared species’ abundances and group sizes between regions.